version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'typescript'
      - dependency-name: 'typedoc'

  - package-ecosystem: 'npm'
    directory: '/website'
    schedule:
      interval: 'daily'
